[package]
name = "startup-module"
version = "0.2.0"
authors = ["Wladimir Palant"]
repository = "https://github.com/pandora-web-server/pandora-web-server"
categories = ["network-programming", "web-programming::http-server"]
keywords = ["proxy", "web-server", "http", "pandora"]
license = "Apache-2.0"
edition = "2021"
rust-version.workspace = true
description = """
A Pandora Web Server module taking care of IP address, port and TLS configuration
"""

[lib]
name = "startup_module"
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
clap.workspace = true
http.workspace = true
pandora-module-utils.workspace = true
pingora.workspace = true
pingora-core.workspace = true
serde.workspace = true

[lints]
workspace = true
